# Generated by Django 2.0 on 2017-12-29 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CensusChangesLog',
            fields=[
                ('current', models.IntegerField()),
                ('before', models.IntegerField()),
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('issue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CensusPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('census', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ns_census_manager.Census')),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='censuspreferences',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ns_census_manager.Nation'),
        ),
        migrations.AddField(
            model_name='census',
            name='values',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ns_census_manager.CensusChangesLog'),
        ),
    ]
